#if USING_UNITY_UI
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using ZarbatanaSystems.BalanceOrchestrator.Pro.Utils;

namespace ZarbatanaSystems.BalanceOrchestrator.Pro.Demo
{
    /// <summary>
    /// Self-contained demo controller for the DDA Engine Pro.
    /// Dynamically binds to the uGUI Canvas generated by CanvasPrefabGenerator
    /// and manages the gameplay simulation in the WorkSpace panel.
    /// </summary>
    public class Pro_DDA_DemoController : MonoBehaviour
    {
        [Header("DDA Settings")]
        [SerializeField] private Pro_DifficultyProfile difficultyProfile;
        
        [Header("Simulation Parameters")]
        [SerializeField] private float baseEnemyHealth = 100f;
        [SerializeField] private float baseEnemySpeed = 3f;
        [SerializeField] private float spawnInterval = 1.5f;

        [Header("UI References (Auto-bound if empty)")]
        [SerializeField] private Text difficultyText;
        [SerializeField] private Text sheetDataText;
        [SerializeField] private Text localDdaText;
        [SerializeField] private Text finalResultText;
        [SerializeField] private RectTransform logContainer;
        [SerializeField] private Text systemLogTitle;
        [SerializeField] private Text logText;
        [SerializeField] private Button fetchButton;
        [SerializeField] private Button strugglingButton;
        [SerializeField] private Button dominatingButton;
        [SerializeField] private RectTransform workSpaceRect;

        private float _sliderDifficulty = 50f;
        private float _lastSpawnTime;
        private List<Pro_DemoEnemy> _activeEnemies = new List<Pro_DemoEnemy>();
        private float _pulseTimer = 0f;

        private float _currentSheetHpMul = 1.0f;
        private float _currentSheetSpeedMul = 1.0f;
        private float _pulseTimerVisual = 0f;
        private Color _originalFinalColor = Color.white;

        // Player GameObject (Blue Center)
        private GameObject _playerGo;
        private Sprite _circleSprite;

        // Workspace boundaries in world coordinates
        private Vector3 _orbitCenter = Vector3.zero;
        private float _orbitRadius = 2.5f;

        // Console logs list
        private List<string> _consoleLogs = new List<string>();
        private float _lastLoggedDifficulty = -1f;

        private void Start()
        {
            // 1. Initialize Pro_DifficultyManager if missing
            if (Pro_DifficultyManager.Instance == null)
            {
                var mgrGo = new GameObject("Pro_DifficultyManager");
                mgrGo.AddComponent<Pro_DifficultyManager>();
            }

            // 2. Ensure default profile is loaded/created
            if (difficultyProfile == null)
            {
                difficultyProfile = ScriptableObject.CreateInstance<Pro_DifficultyProfile>();
                difficultyProfile.description = "Default programmatically generated profile for PRO Demo.";
                difficultyProfile.enemyHealthMul = AnimationCurve.Linear(0f, 0.5f, 100f, 2.5f);
                difficultyProfile.enemySpeedMul = AnimationCurve.Linear(0f, 0.5f, 100f, 2.0f);
                difficultyProfile.enemySpawnChanceMul = AnimationCurve.Linear(0f, 0.5f, 100f, 2.0f);
                difficultyProfile.waveDelayMul = AnimationCurve.Linear(0f, 2.0f, 100f, 0.5f);
                difficultyProfile.rewardMul = AnimationCurve.Linear(0f, 0.5f, 100f, 2.0f);
                difficultyProfile.abilityIntensityMul = AnimationCurve.Linear(0f, 0.5f, 100f, 2.0f);
                difficultyProfile.defaultDifficultyPercentage = 50f;
            }

            _sliderDifficulty = difficultyProfile.defaultDifficultyPercentage;
            Pro_DifficultyManager.Instance.Initialize(difficultyProfile, _sliderDifficulty);
            Pro_DifficultyManager.Instance.SetDdaEnabled(true);
            Pro_DifficultyManager.Instance.SetDdaCooldown(2f); // Lower cooldown for immediate feedback in demo

            // 3. Auto-bind UI references
#if UNITY_2023_1_OR_NEWER
            var canvas = FindAnyObjectByType<Canvas>();
#else
            var canvas = FindObjectOfType<Canvas>();
#endif
            if (canvas != null)
            {
                if (difficultyText == null) difficultyText = FindDeepChild<Text>(canvas.transform, "DifficultyText");
                if (sheetDataText == null) sheetDataText = FindDeepChild<Text>(canvas.transform, "SheetDataText");
                if (localDdaText == null) localDdaText = FindDeepChild<Text>(canvas.transform, "LocalDdaText");
                if (finalResultText == null) finalResultText = FindDeepChild<Text>(canvas.transform, "FinalResultText");
                if (logContainer == null)
                {
                    var lc = FindDeepChild<Transform>(canvas.transform, "LogContainer");
                    if (lc != null) logContainer = lc as RectTransform;
                }
                if (systemLogTitle == null) systemLogTitle = FindDeepChild<Text>(canvas.transform, "SystemLogTitle");
                if (logText == null) logText = FindDeepChild<Text>(canvas.transform, "LogText");
                
                if (fetchButton == null) fetchButton = FindDeepChild<Button>(canvas.transform, "FetchButton");
                if (strugglingButton == null) strugglingButton = FindDeepChild<Button>(canvas.transform, "StrugglingButton");
                if (dominatingButton == null) dominatingButton = FindDeepChild<Button>(canvas.transform, "DominatingButton");
                
                if (workSpaceRect == null)
                {
                    var ws = FindDeepChild<Transform>(canvas.transform, "WorkSpace");
                    if (ws != null) workSpaceRect = ws as RectTransform;
                }
            }

            if (finalResultText != null)
            {
                _originalFinalColor = finalResultText.color;
            }

            // 4. Hook button click events
            if (fetchButton != null) fetchButton.onClick.AddListener(OnFetchClicked);
            if (strugglingButton != null) strugglingButton.onClick.AddListener(OnStrugglingClicked);
            if (dominatingButton != null) dominatingButton.onClick.AddListener(OnDominatingClicked);

            // 5. Generate sprites & spawn player
            _circleSprite = CreateCircleSprite(128);
            UpdateWorkspaceBounds();
            SpawnPlayer();

            UpdateSheetMultipliersFromManager();

            AddLog("System initialized. DDA Mode is Active.", Color.green);
            if (Pro_DDA_Manager.Instance != null && !string.IsNullOrEmpty(Pro_DDA_Manager.Instance.DataSource))
            {
                AddLog($"Synced Data Source: {Pro_DDA_Manager.Instance.DataSource.Substring(0, Mathf.Min(8, Pro_DDA_Manager.Instance.DataSource.Length))}...", Color.yellow);
            }
        }

        private void Update()
        {
            if (_pulseTimer > 0f)
            {
                _pulseTimer -= Time.deltaTime;
            }

            // Read dynamic updates from the difficulty manager
            float currentPercent = Pro_DifficultyManager.Instance.GetCurrentPercent();
            var snapshot = Pro_DifficultyManager.Instance.Get();

            UpdateFormulaUI();

            // Visual pulse feedback for FINAL RESULT text
            if (_pulseTimerVisual > 0f)
            {
                _pulseTimerVisual -= Time.deltaTime;
                float t = Mathf.Clamp01(_pulseTimerVisual / 0.5f);
                
                if (finalResultText != null)
                {
                    finalResultText.color = Color.Lerp(_originalFinalColor, Color.green, t);
                    float scale = 1f + Mathf.Sin(t * Mathf.PI) * 0.15f;
                    finalResultText.transform.localScale = new Vector3(scale, scale, 1f);
                }
            }
            else
            {
                if (finalResultText != null)
                {
                    finalResultText.color = _originalFinalColor;
                    finalResultText.transform.localScale = Vector3.one;
                }
            }

            // Log percentage adjustments automatically
            if (!Mathf.Approximately(currentPercent, _lastLoggedDifficulty))
            {
                if (_lastLoggedDifficulty >= 0f)
                {
                    string direction = currentPercent > _lastLoggedDifficulty ? "increased" : "reduced";
                    string icon = currentPercent > _lastLoggedDifficulty ? "🔥" : "⚠️";
                    Color logColor = currentPercent > _lastLoggedDifficulty ? new Color(1f, 0.4f, 0.4f) : new Color(0.6f, 0.8f, 1f);
                    AddLog($"{icon} DDA {direction} difficulty to {currentPercent:F1}%", logColor);
                }
                _lastLoggedDifficulty = currentPercent;
            }

            // Spawn loop
            float adjustedInterval = spawnInterval * snapshot.waveDelayMul;
            if (Time.time - _lastSpawnTime > adjustedInterval)
            {
                SpawnEnemyCircle();
                _lastSpawnTime = Time.time;
            }

            // Keep player positioned at the center of workspace
            UpdateWorkspaceBounds();
            if (_playerGo != null)
            {
                _playerGo.transform.position = _orbitCenter;
            }

            // Orbit enemy movement & lifecycle
            for (int i = _activeEnemies.Count - 1; i >= 0; i--)
            {
                var enemy = _activeEnemies[i];
                if (enemy == null || enemy.gameObject == null)
                {
                    _activeEnemies.RemoveAt(i);
                    continue;
                }

                enemy.lifetime += Time.deltaTime;

                // Stats calculation based on base value * sheet multiplier * DDA snapshot
                enemy.currentHP = baseEnemyHealth * _currentSheetHpMul * snapshot.enemyHealthMul;
                enemy.currentSpeed = baseEnemySpeed * _currentSheetSpeedMul * snapshot.enemySpeedMul;

                // Move along orbital circle path
                enemy.angle += enemy.speedDirection * enemy.currentSpeed * Time.deltaTime / enemy.radius;
                enemy.transform.position = _orbitCenter + new Vector3(Mathf.Cos(enemy.angle), Mathf.Sin(enemy.angle), 0f) * enemy.radius;

                // Calculate visual scaling and three-way lerp color
                float p = currentPercent / 100f;
                Color targetColor;
                float visualScaleMul;

                if (p < 0.5f)
                {
                    float t = p / 0.5f;
                    targetColor = Color.Lerp(Color.green, Color.yellow, t);
                    visualScaleMul = Mathf.Lerp(0.5f, 1.0f, t);
                }
                else
                {
                    float t = (p - 0.5f) / 0.5f;
                    targetColor = Color.Lerp(Color.yellow, Color.red, t);
                    visualScaleMul = Mathf.Lerp(1.0f, 2.0f, t);
                }

                // Apply pulse animation multiplier
                float pulseMul = 1f;
                if (_pulseTimer > 0f)
                {
                    pulseMul = 1f + Mathf.Sin(_pulseTimer * Mathf.PI * 4f) * 0.2f;
                }

                // Update size and color
                float scale = 0.5f * visualScaleMul * _currentSheetHpMul * pulseMul;
                enemy.transform.localScale = new Vector3(scale, scale, scale);

                var spriteRenderer = enemy.GetComponent<SpriteRenderer>();
                if (spriteRenderer != null)
                {
                    // Lifetime fade out over the last 2 seconds
                    float alpha = 1f;
                    if (enemy.lifetime > 10f)
                    {
                        alpha = Mathf.Clamp01(1f - (enemy.lifetime - 10f) / 2f);
                    }
                    spriteRenderer.color = new Color(targetColor.r, targetColor.g, targetColor.b, alpha);

                    // Update trail color and width
                    var trail = enemy.GetComponent<TrailRenderer>();
                    if (trail != null)
                    {
                        trail.startColor = new Color(targetColor.r, targetColor.g, targetColor.b, alpha * 0.8f);
                        trail.endColor = new Color(targetColor.r, targetColor.g, targetColor.b, 0f);
                        trail.startWidth = scale * 0.4f;
                    }

                    // Update floating world space label text & fade
                    if (enemy.floatingText != null)
                    {
                        enemy.floatingText.text = $"HP: <color=#ffaaaa>{enemy.currentHP:F0}</color>\nSpd: <color=#ffff44>{enemy.currentSpeed:F1}</color>";
                        enemy.floatingText.color = new Color(1f, 1f, 1f, alpha);

                        var bgImage = enemy.floatingText.transform.parent.GetComponent<Image>();
                        if (bgImage != null)
                        {
                            bgImage.color = new Color(0f, 0f, 0f, 0.5f * alpha);
                        }
                    }
                }

                // Destroy after 12 seconds
                if (enemy.lifetime >= 12f)
                {
                    Destroy(enemy.gameObject);
                    _activeEnemies.RemoveAt(i);
                }
            }
        }

        private void SpawnEnemyCircle()
        {
            if (_activeEnemies.Count >= 8) return;

            GameObject enemyGo = new GameObject("DemoEnemyCircle");
            var spriteRenderer = enemyGo.AddComponent<SpriteRenderer>();
            spriteRenderer.sprite = _circleSprite;
            spriteRenderer.color = Color.green;

            // Add dynamic trail
            var trail = enemyGo.AddComponent<TrailRenderer>();
            trail.time = 1.2f;
            trail.startWidth = 0.2f;
            trail.endWidth = 0f;
            trail.material = new Material(Shader.Find("Sprites/Default"));
            trail.sortingOrder = 4;

            var enemyComp = enemyGo.AddComponent<Pro_DemoEnemy>();
            enemyComp.radius = _orbitRadius * UnityEngine.Random.Range(0.7f, 1.3f);
            enemyComp.angle = UnityEngine.Random.Range(0f, Mathf.PI * 2f);
            enemyComp.speedDirection = UnityEngine.Random.value > 0.5f ? 1f : -1f;
            enemyComp.lifetime = 0f;
            enemyComp.currentHP = baseEnemyHealth;
            enemyComp.currentSpeed = baseEnemySpeed;

            // Generate World-Space floating label text
            enemyComp.floatingText = CreateWorldSpaceLabel(enemyGo, "HP: 100\nSpd: 3.0", Color.white);

            _activeEnemies.Add(enemyComp);
        }

        private void SpawnPlayer()
        {
            if (_playerGo != null) Destroy(_playerGo);

            _playerGo = new GameObject("PlayerCircle");
            var spriteRenderer = _playerGo.AddComponent<SpriteRenderer>();
            spriteRenderer.sprite = _circleSprite;
            spriteRenderer.color = new Color(0.2f, 0.6f, 1f); // Vibrant Blue
            spriteRenderer.sortingOrder = 5;

            _playerGo.transform.localScale = new Vector3(0.8f, 0.8f, 0.8f);
            _playerGo.transform.position = _orbitCenter;

            // Label above player
            CreateWorldSpaceLabel(_playerGo, "<b><color=#55ccff>PLAYER</color></b>", Color.cyan);
        }

        private void UpdateWorkspaceBounds()
        {
            if (workSpaceRect != null && Camera.main != null)
            {
                Vector3[] corners = new Vector3[4];
                workSpaceRect.GetWorldCorners(corners);
                
                Vector3 worldBottomLeft = Camera.main.ScreenToWorldPoint(new Vector3(corners[0].x, corners[0].y, 10f));
                Vector3 worldTopRight = Camera.main.ScreenToWorldPoint(new Vector3(corners[2].x, corners[2].y, 10f));
                
                _orbitCenter = (worldBottomLeft + worldTopRight) * 0.5f;
                _orbitCenter.z = 0f;
                
                float w = worldTopRight.x - worldBottomLeft.x;
                float h = worldTopRight.y - worldBottomLeft.y;
                _orbitRadius = Mathf.Min(w, h) * 0.35f;
            }
            else
            {
                bool isPortrait = Screen.width < Screen.height;
                _orbitCenter = isPortrait ? new Vector3(0f, -2.5f, 0f) : new Vector3(0f, -0.5f, 0f);
                _orbitRadius = isPortrait ? 1.8f : 2.5f;
            }
        }

        private Text CreateWorldSpaceLabel(GameObject parentGo, string initialText, Color textColor)
        {
            GameObject canvasGo = new GameObject("WorldLabelCanvas");
            canvasGo.transform.SetParent(parentGo.transform, false);
            canvasGo.transform.localPosition = new Vector3(0f, 0.9f, 0f);
            
            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;
            
            RectTransform canvasRect = canvasGo.GetComponent<RectTransform>();
            canvasRect.sizeDelta = new Vector2(280, 110);
            canvasRect.localScale = new Vector3(0.005f, 0.005f, 1f); // Keep it sized correctly
            
            // Add a semi-transparent dark background image for readability
            Image bgImage = canvasGo.AddComponent<Image>();
            bgImage.color = new Color(0f, 0f, 0f, 0.5f);

            GameObject textGo = new GameObject("LabelText");
            textGo.transform.SetParent(canvasGo.transform, false);
            
            RectTransform textRect = textGo.AddComponent<RectTransform>();
            textRect.anchorMin = Vector2.zero;
            textRect.anchorMax = Vector2.one;
            textRect.sizeDelta = Vector2.zero;
            textRect.anchoredPosition = Vector2.zero;
            
            Text text = textGo.AddComponent<Text>();
            Font customFont = null;
            try
            {
                customFont = (Font)Resources.GetBuiltinResource(typeof(Font), "Arial.ttf");
            }
            catch (System.ArgumentException)
            {
                customFont = (Font)Resources.GetBuiltinResource(typeof(Font), "LegacyRuntime.ttf");
            }
            
            text.font = customFont;
            text.fontSize = 32;
            text.alignment = TextAnchor.MiddleCenter;
            text.text = initialText;
            text.color = textColor;
            text.supportRichText = true;
            
            var outline = textGo.AddComponent<Outline>();
            outline.effectColor = Color.black;
            outline.effectDistance = new Vector2(1.5f, -1.5f);
            
            return text;
        }

        private Sprite CreateCircleSprite(int size = 128)
        {
            Texture2D tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            float center = size / 2f;
            float radius = (size / 2f) - 3f;
            
            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float dist = Vector2.Distance(new Vector2(x, y), new Vector2(center, center));
                    if (dist < radius - 1f)
                    {
                        tex.SetPixel(x, y, Color.white);
                    }
                    else if (dist < radius + 1f)
                    {
                        float alpha = 1f - Mathf.Clamp01((dist - (radius - 1f)) / 2f);
                        tex.SetPixel(x, y, new Color(1f, 1f, 1f, alpha));
                    }
                    else
                    {
                        tex.SetPixel(x, y, Color.clear);
                    }
                }
            }
            tex.Apply();
            return Sprite.Create(tex, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), size);
        }

        private void OnFetchClicked()
        {
            if (Pro_DDA_Manager.Instance == null) return;
            
            AddLog("🔄 Syncing Google Sheet in background...", Color.yellow);
            Pro_DDA_Manager.Instance.FetchDataFromSheet((success, message) => {
                if (success)
                {
                    AddLog("✔️ Sheet balance fetched and updated successfully!", Color.green);
                    UpdateSheetMultipliersFromManager();
                }
                else
                {
                    AddLog($"❌ Sync failed: {message}", Color.red);
                }
            });
        }

        private void UpdateSheetMultipliersFromManager()
        {
            if (Pro_DDA_Manager.Instance != null)
            {
                var rowData = Pro_DDA_Manager.Instance.GetRowData("Level_1");
                if (rowData != null)
                {
                    _currentSheetHpMul = rowData.GetFloat("HpMultiplier", fallback: 1.0f);
                    _currentSheetSpeedMul = rowData.GetFloat("SpeedMultiplier", fallback: 1.0f);

                    // Reset DDA Difficulty percentage to the target difficulty defined in Google Sheets!
                    string rawDiffVal = rowData.ContainsKey("DifficultyPercentage") ? rowData["DifficultyPercentage"] : "N/A";
                    float targetDiff = rowData.GetFloat("DifficultyPercentage", fallback: 50.0f);
                    
                    Debug.Log($"[Pro DDA Demo] Fetched row 'Level_1': HP Mul={_currentSheetHpMul}, Speed Mul={_currentSheetSpeedMul}, Raw Difficulty='{rawDiffVal}', Parsed Difficulty={targetDiff}%");

                    if (Pro_DifficultyManager.Instance != null)
                    {
                        Pro_DifficultyManager.Instance.Evaluate(targetDiff);
                        Debug.Log($"[Pro DDA Demo] Evaluated Pro_DifficultyManager with new difficulty: {targetDiff}%");
                    }
                    else
                    {
                        Debug.LogWarning("[Pro DDA Demo] Pro_DifficultyManager.Instance is null!");
                    }

                    TriggerFinalResultPulse();
                }
                else
                {
                    Debug.LogWarning("[Pro DDA Demo] Row 'Level_1' not found in DDA Manager data!");
                    _currentSheetHpMul = 1.0f;
                    _currentSheetSpeedMul = 1.0f;
                }
            }
            UpdateFormulaUI();
        }

        private void TriggerFinalResultPulse()
        {
            _pulseTimerVisual = 0.5f;
        }

        private void UpdateFormulaUI()
        {
            float currentPercent = Pro_DifficultyManager.Instance.GetCurrentPercent();
            var snapshot = Pro_DifficultyManager.Instance.Get();

            if (difficultyText != null)
            {
                difficultyText.text = $"Current Difficulty: <color=#00ffcc><b>{currentPercent:F1}%</b></color>";
            }

            if (sheetDataText != null)
            {
                sheetDataText.text = $"☁️ Sheet Data (Cloud): HP <color=#ffff44>x{_currentSheetHpMul:F2}</color> | Spd <color=#ffff44>x{_currentSheetSpeedMul:F2}</color>";
            }

            if (localDdaText != null)
            {
                localDdaText.text = $"🧠 Local DDA (Runtime): HP <color=#ffff44>x{snapshot.enemyHealthMul:F2}</color> | Spd <color=#ffff44>x{snapshot.enemySpeedMul:F2}</color>";
            }

            float finalHpMul = _currentSheetHpMul * snapshot.enemyHealthMul;
            float finalSpeedMul = _currentSheetSpeedMul * snapshot.enemySpeedMul;

            if (finalResultText != null)
            {
                finalResultText.text = $"🔥 <b>FINAL RESULT: HP <color=#ff4444>x{finalHpMul:F2}</color> | Spd <color=#ff4444>x{finalSpeedMul:F2}</color></b>";
            }
        }

        private void OnStrugglingClicked()
        {
            AddLog("Simulated Event: Player Struggling (Low Safety)", Color.yellow);
            Pro_DifficultyManager.Instance.TryReport(Pro_DdaEvent.SafetyRatio01, 0.1f);
            _pulseTimer = 0.5f;
        }

        private void OnDominatingClicked()
        {
            AddLog("Simulated Event: Player Dominating (High Safety)", Color.yellow);
            Pro_DifficultyManager.Instance.TryReport(Pro_DdaEvent.SafetyRatio01, 0.9f);
            _pulseTimer = 0.5f;
        }

        private void AddLog(string msg, Color color)
        {
            string hexColor = ColorUtility.ToHtmlStringRGBA(color);
            _consoleLogs.Add($"<color=#{hexColor}>{msg}</color>");
            if (_consoleLogs.Count > 5)
            {
                _consoleLogs.RemoveAt(0);
            }

            if (logText != null)
            {
                logText.text = string.Join("\n", _consoleLogs);
            }
        }

        private T FindDeepChild<T>(Transform parent, string name) where T : Component
        {
            foreach (Transform child in parent.GetComponentsInChildren<Transform>(true))
            {
                if (child.name == name)
                {
                    var component = child.GetComponent<T>();
                    if (component != null) return component;
                }
            }
            return null;
        }
    }

    public class Pro_DemoEnemy : MonoBehaviour
    {
        public float currentHP;
        public float currentSpeed;
        public float angle;
        public float radius;
        public float speedDirection;
        public float lifetime;
        public Text floatingText;
    }
}
#endif
